### ISSUE TITLE
[Solved - Version 0.2.9] Crashes on startup NoSuchMethodError: net.minecraft.block.Block.getRegistryName

### ISSUE THREAD

**Issue by Melakion** [jtmnf/SimpleOreGenerator#1]
http://pastebin.com/kSqNewQZ

MC 1.9 - Forge 1854 - simpleoregen-1.9-0.2.6

**Comment by jtmnf** [comment]
The build was made in 1811, but I will upload it to the last one, the 1854.
Thanks for the notification :)

**Comment by jtmnf** [comment]
Fixed in version 0.2.7
