### ISSUE TITLE
[Solved - Version 0.4.2] filter/use ores with block metadata

### ISSUE THREAD

**Issue by 4rz0** [jtmnf/SimpleOreGenerator#2]
I tried modifying ore-spawn of Forestry and Mekanims mores, however, those ore-blocks use metadata, which seems to cause problems.
Now I tried adding those in a general fashion to the config (commands.xml for now to experiment with it), like `<block>forestry:resources:1</block>` for copper, `<block>forestry:resources:1</block>` for tin etc.

However, when using the commands (after restarting the client), these ores still get removed.
I haven't tried modifying ore-generation like that, but I assume the same happens there.

**Comment by jtmnf** [comment]
Thanks for the report! I'll try to fix that until August 20th!

**Comment by jtmnf** [comment]
I fixed it, but the nomenclature is different...
Some examples:
Andesite: **minecraft:stone[variant=andesite]**
IE Copper: **immersiveengineering:ore[variants=copper]**
Forestry Tin: **forestry:resources[resources=tin]**

**Comment by jtmnf** [comment]
The version 0.4.2 fixes almost all problems, but the next version (0.4.3) that I'll sent tomorrow will fix everything :)
